Repository manamarumi/DiverCityVancouver, pull requests merged in 2024-03, with the labels that each got.

#69 App goes to homepage after signing out.
  Divercity-Vancouver/src/components/navbar.jsx
Labels: bug

#73 change password updated
  Divercity-Vancouver/.env
  Divercity-Vancouver/package-lock.json
  Divercity-Vancouver/package.json
  Divercity-Vancouver/src/components/navbar.jsx
  Divercity-Vancouver/src/firebase.js
  Divercity-Vancouver/src/pages/ChangePassword/ChangePassword.jsx
  Divercity-Vancouver/src/pages/Customer/ForgotPassword/ForgotPassword.jsx
  Divercity-Vancouver/src/pages/Homepage/homepage.jsx
Labels: documentation, enhancement

#75 Prevent goback login and signup setting
  Divercity-Vancouver/src/App.jsx
  Divercity-Vancouver/src/components/ProtectedRoutes.jsx
  Divercity-Vancouver/src/pages/Customer/Login/Login.jsx
Labels: documentation

#84 subcribe button works
  Divercity-Vancouver/src/firebase.js
  Divercity-Vancouver/src/pages/Admin/adminpage.jsx
  Divercity-Vancouver/src/pages/Admin/postevents.jsx
  Divercity-Vancouver/src/pages/Admin/postnews.jsx
  Divercity-Vancouver/src/pages/Customer/Signuppage/signuppage.jsx
  Divercity-Vancouver/src/pages/EditUserProfile/EditUserProfile.jsx
  Divercity-Vancouver/src/pages/MonthlyEventView/MonthlyEventView.jsx
  Divercity-Vancouver/src/pages/Subscription/Subscription.jsx
  Divercity-Vancouver/src/pages/UserProfile/UserProfile.jsx
Labels: enhancement

#92 Like button are working on the homepage but not syncing with firebase
  Divercity-Vancouver/src/pages/Homepage/homepage.jsx
Labels: enhancement

#93 shrink cards and search fucntion updated
  Divercity-Vancouver/src/App.jsx
  Divercity-Vancouver/src/components/navbar.jsx
  Divercity-Vancouver/src/pages/Admin/adminpage.jsx
  Divercity-Vancouver/src/pages/ExploreEvent/ExploreEvent.jsx
  Divercity-Vancouver/src/pages/ExploreNews/ExploreNews.jsx
  Divercity-Vancouver/src/pages/Homepage/homepage.jsx
  Divercity-Vancouver/src/pages/MonthlyEventView/MonthlyEventView.jsx
Labels: enhancement

#95 sharnk cards and firebase permit change
  Divercity-Vancouver/src/firebase.js
  Divercity-Vancouver/src/pages/Homepage/homepage.jsx
Labels: bug, enhancement
